### ISSUE TITLE
error with websocket

### ISSUE THREAD

**Issue by ankanani** [pollev/santas_little_helper#1]
Hi I am getting this error on execution:

```
ubuntu:~/Documents/GitHub/santas_little_helper$ python3 santas_little_helper.py
Traceback (most recent call last):
  File "santas_little_helper.py", line 33, in <module>
    ws = websocket.WebSocket(sslopt={"cert_reqs": ssl.CERT_NONE})
TypeError: __init__() got an unexpected keyword argument 'sslopt'
```

Any idea how to fix this?
Thanks
AK

**Comment by pollev** [comment]
Hello!

It seems like you are missing the correct websocket dependency.
Please run

`python3 -m pip install websocket_client`

I will add this to the readme as well.

**Comment by ankanani** [comment]
thank you Polle!
The script is executing now.
However, tt seems Kringlecon server is dead at the moment, so cannot try it
fully though.
Will let you know if i face any more issues.
Regards

**Comment by pollev** [comment]
They seem down indeed. However it seems that the other endpoints are still up and running. For example the splunk interface is still up at https://splunk.elfu.org. Or all of the terminal challenges are also still working. For example: https://docker2019.kringlecon.com/?challenge=iptables

If you are interested in doing some challenges, I have the direct URLs for most of them in my writeup at https://pollev.github.io/Kringlecon-2-Turtle-Doves/

My apologies that the writeup is not complete yet. It is quite a big wall of text to work on.

**Comment by ankanani** [comment]
I am done with all but the last objective 12. Spent like 3 days on it but
no luck, giving up now.
I have got around 65 confirmed bad IP addresses doing LFI, XSS, SQLi.
However the pivot part, I tried so many combinations, but none worked.
I just dont know if I am going in the right direction. If i get one or two
confirmed bad addresses obtained by pivoting, then i can try further, else
i am just going to pass for this one. It is frustrating.
Are you done with all the challenges?

**Comment by ankanani** [comment]
I just saw your writeup, very nice effort in documenting everything.
All the best for submission for the winning entry.
And good luck for the remaining challenges.
8,9,10 are really good and involves some work. 11 is also good, you will be
able to finish it quickly. and dont ask about 12 :-)
Happy holidays!

**Comment by pollev** [comment]
Hi,
We finished all except 12. Going to try it today!

**Comment by ankanani** [comment]
good luck, let me know how it goes.
Anand

**Comment by pollev** [comment]
Well, we will see if the servers come back online today. I still need the credentials to login to the sled machine thing. But I suppose the elf standing next to it is going to give me those...

**Comment by ankanani** [comment]
The elf wont give the credentials. The ELF just tells you to look for bad
IPs in the logs. And some hints.
This is the website:https://srf.elfu.org/
And if you have the zeek logs, then you can start working on the challenge.
The credentials are supposed to be found by you as the first step, by
analyzing the logs.
Anand

**Comment by ankanani** [comment]
i managed to finally crack the last one. so all done now. :-)
Also i tested your script. It worked wonderfully.
Happy Holidays!
and good luck for the rest of the challenges!
Cheers
Anand
